In [ ]:
assignment 3



1

In [5]:
import numpy as np

In [ ]:
arr1=np.arange(1,11)

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2

In [ ]:
arr2=np.zeros((2,3))

In [ ]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

3

In [ ]:
arr3=np.arange(2,21,2)

In [ ]:
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr2=np.array([4,5,6])

In [ ]:
arr1+arr2

array([5, 7, 9])

In [ ]:
arr1-arr2

array([-3, -3, -3])

In [ ]:
arr1*arr2


array([ 4, 10, 18])

In [ ]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

5

In [ ]:
arr1=np.random.randint(1,101,100)

In [ ]:
arr1

array([  5,  29,  19,  55,  77,  40,  65,  65,  80,  27,  69,  23,  48,
        56,  78,  80,  24,  35,  71,  14,  36,  36,  57,  34,  25,  70,
        78,  22,  85,  46,  81,  96,  37,  14,   9,  27,  28,   7,  89,
        16,  98,  24,  50,  48,  57,  85,  26,  38,  54,  21,  86, 100,
         5,  18,   3,  28,  15,  75,  71,  54,  59,  49,  14,  39,  94,
         8,  63,  50,  26,  32,  39,  95,  62,  84,  36,  48,  12,  92,
        52,  30,  97,  55,  33,  36,  22,  13,  75,  51,  16,  37,  70,
        52,   4,  29,  18,  82,  82,   3,  23,  91])

6

In [ ]:
arr1=np.random.randint(1,101,12)


In [ ]:
arr1

array([70, 39, 61, 84, 34, 30, 85, 17, 91, 40, 14,  6])

In [ ]:
arr1.reshape(3,4)

array([[70, 39, 61, 84],
       [34, 30, 85, 17],
       [91, 40, 14,  6]])

7

In [ ]:
arr=np.array([1,2,3,4,5])
np.square(arr)

array([ 1,  4,  9, 16, 25])

8

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
a.dot(b)

32

10

In [6]:
arr1=np.random.randint(1,101,10)

In [7]:
arr1

array([98, 20, 77, 95, 86, 33, 47, 75, 42, 12])

In [8]:
arr1.argmax()

0

In [9]:
arr1.argmin()

9

11

In [14]:
a=np.zeros((4,4))
b=np.ones((4,4))
c=np.concatenate((a,b))
d=np.concatenate((a,b),axis=1)
print('vertical concatenation-\n',c)
print('horizontal concatenation-\n',d)

vertical concatenation-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
horizontal concatenation-
 [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


12

In [15]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print('sum of each column is',np.sum(arr,axis=0))
print('sum of each row is',np.sum(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum of each column is [28 32 36 40]
sum of each row is [10 26 42 58]


13

In [16]:
a=np.array([[4,9],[5,8],[6,7]])
b=np.array([[3,9],[5,2],[6,7]])
c=np.intersect1d(a,b)
print("the common elements between a and b are",c)

the common elements between a and b are [5 6 7 9]


14

In [17]:
x=np.array([1,2,3,-4,-5,-6])
x[x<0]=0
x

array([1, 2, 3, 0, 0, 0])

15

In [18]:
arr1=np.random.randint(1,101,100)
arr1.sort()
arr1

array([ 1,  4,  5,  7,  7, 10, 10, 10, 11, 11, 11, 12, 13, 15, 15, 16, 19,
       19, 23, 24, 26, 27, 27, 27, 29, 30, 35, 35, 35, 35, 36, 36, 37, 38,
       39, 41, 41, 42, 43, 44, 45, 48, 50, 52, 53, 54, 54, 54, 55, 55, 55,
       55, 56, 56, 56, 58, 58, 59, 59, 62, 65, 66, 66, 67, 69, 69, 70, 72,
       72, 73, 75, 75, 76, 77, 77, 79, 80, 82, 82, 83, 83, 84, 84, 85, 85,
       86, 87, 87, 87, 87, 88, 89, 89, 90, 90, 90, 94, 98, 99, 99])

16

In [20]:
a=np.array([1,2,3,4,5])
b=np.array([6,8,10,12,14])
c=np.absolute(a-b)
print("the element-wise absolute difference between the two arrays is",c)

the element-wise absolute difference between the two arrays is [5 6 7 8 9]


17

In [22]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
firstrow=arr[0]
lastcol=arr[:,[-1]]
print("first row is\n",firstrow)
print("last coluymn is\n",lastcol)

first row is
 [1 2 3]
last coluymn is
 [[3]
 [6]
 [9]]


18

In [24]:
a=np.array([1,2,3,4,5])
x=a[0:len(a)+1]
print(x)

[1 2 3 4 5]


19

In [25]:
arr=np.array([[10,1,14,16,18,20],[22,24,26,28,30,32],[34,36,38,40,42,44],[46,48,50,52,54,56],[58,60,62,64,66,68],[70,72,74,76,78,80]])
x=arr[2:4,[2,3]]
print('original array is\n',arr)
print('central 2x2 elements include\n',x)

original array is
 [[10  1 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]
central 2x2 elements include
 [[38 40]
 [50 52]]


20

In [26]:
a=np.array([1,2,3,4,5])
x=a[::-1]
x

array([5, 4, 3, 2, 1])